package com.bluebyte.app

import kotlin.random.Random

object FortuneUtils {
    private val fortunes = listOf(
        "A closed mouth gathers no feet.",
        "A conclusion is the place where you got tired of thinking.",
        "A cynic is only a frustrated optimist.",
        "A fanatic is one who can't change his mind and won't change the subject.",
        "A friend is someone who knows all about you and still likes you.",
        "A great way to keep your secrets is to tell them to everyone.",
        "A journey of a thousand miles begins with a single step.",
        "A man who has no enemies has no friends.",
        "A person who never made a mistake never tried anything new.",
        "A pessimist is a person who has to listen to too many optimists.",
        "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.",
        "Action is the foundational key to all success.",
        "All our dreams can come true, if we have the courage to pursue them.",
        "Always forgive your enemies; nothing annoys them so much.",
        "An eye for an eye only ends up making the whole world blind.",
        "Be yourself; everyone else is already taken.",
        "Believe you can and you're halfway there.",
        "Change your thoughts and you change your world.",
        "Do one thing every day that scares you.",
        "Dream big and dare to fail.",
        "Everything has beauty, but not everyone sees it.",
        "Failure is the condiment that gives success its flavor.",
        "Happiness is not something ready made. It comes from your own actions.",
        "If you want to live a happy life, tie it to a goal, not to people or things.",
        "Imagination is more important than knowledge.",
        "It always seems impossible until it's done.",
        "Life is what happens when you're busy making other plans.",
        "Success is not final, failure is not fatal: it is the courage to continue that counts.",
        "The best way to predict the future is to invent it.",
        "The only way to do great work is to love what you do.",
        "To be or not to be, that is the question.",
        "The cake is a lie.",
        "Do, or do not. There is no try.",
        "I've seen things you people wouldn't believe.",
        "All those moments will be lost in time, like tears in rain.",
        "Resistance is futile.",
        "Computers are like Old Testament gods; lots of rules and no mercy.",
        "To err is human, but to really foul things up you need a computer.",
        "Artificial intelligence is no match for natural stupidity.",
        "Hardware: The parts of a computer system that can be kicked.",
        "I'm sorry, Dave. I'm afraid I can't do that.",
        "It's a trap!",
        "Live long and prosper.",
        "Never tell me the odds.",
        "I find your lack of faith disturbing.",
        "Stay hungry, stay foolish.",
        "The computer was born to solve problems that did not exist before.",
        "Technology is a useful servant but a dangerous master.",
        "The most advanced technology is indistinguishable from magic.",
        "Programs must be written for people to read, and only incidentally for machines to execute.",
        "Digital design is like painting with light.",
        "Your most unhappy customers are your greatest source of learning.",
        "Data is the new oil.",
        "The best error message is the one that never appears.",
        "Everything is a file.",
        "In space, no one can hear you scream.",
        "Keep it simple, stupid.",
        "Don't panic.",
        "42 is the answer to life, the universe, and everything.",
        "So long, and thanks for all the fish.",
        "I think, therefore I am.",
        "What is real? How do you define 'real'?",
        "There is no spoon.",
        "Wake up, Neo...",
        "Follow the white rabbit.",
        "The grid. A digital frontier.",
        "User on the line.",
        "End of line.",
        "Greetings, Programs!",
        "I'll be back.",
        "Hasta la vista, baby.",
        "Go ahead, make my day.",
        "I'm the king of the world!",
        "Houston, we have a problem.",
        "You're gonna need a bigger boat.",
        "Keep your friends close, but your enemies closer.",
        "I'm going to make him an offer he can't refuse.",
        "There's no place like home.",
        "Toto, I've a feeling we're not in Kansas anymore.",
        "Here's looking at you, kid.",
        "Frankly, my dear, I don't give a damn.",
        "The truth is out there.",
        "Trust no one.",
        "I want to believe.",
        "Everything that has a beginning has an end.",
        "The future is not set. There is no fate but what we make.",
        "You either die a hero, or you live long enough to see yourself become the villain.",
        "Why so serious?",
        "With great power comes great responsibility.",
        "I am Iron Man.",
        "Avengers, assemble!",
        "I can do this all day.",
        "Wakanda Forever!",
        "To infinity and beyond!",
        "Just keep swimming.",
        "Adventure is out there!",
        "Elementary, my dear Watson.",
        "Great Scott!",
        "Heavy.",
        "This is the way.",
        "I have spoken.",
        "One ring to rule them all.",
        "Fly, you fools!",
        "You shall not pass!",
        "My precious...",
        "Winter is coming.",
        "A Lannister always pays his debts.",
        "Chaos is a ladder.",
        "Not all who wander are lost.",
        "Not all those who wander are lost.",
        "Simplicity is the ultimate sophistication.",
        "The details are not the details. They make the design.",
        "Design is not just what it looks like and feels like. Design is how it works.",
        "Standardized minds are the products of standardized schools.",
        "Everything should be made as simple as possible, but not simpler.",
        "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.",
        "Imagination is the highest form of research.",
        "The important thing is not to stop questioning.",
        "Learn from yesterday, live for today, hope for tomorrow.",
        "A person starts to live when he can live outside himself.",
        "Logic will get you from A to B. Imagination will take you everywhere.",
        "I have no special talent. I am only passionately curious.",
        "Peace cannot be kept by force; it can only be achieved by understanding.",
        "We cannot solve our problems with the same thinking we used when we created them.",
        "The measure of intelligence is the ability to change.",
        "Life is like riding a bicycle. To keep your balance, you must keep moving.",
        "Creativity is intelligence having fun.",
        "Look deep into nature, and then you will understand everything better.",
        "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.",
        "Only a life lived for others is a life worthwhile.",
        "A table, a chair, a bowl of fruit and a violin; what else does a man need to be happy?",
        "I am enough of an artist to draw freely upon my imagination.",
        "Information is not knowledge.",
        "The only source of knowledge is experience.",
        "He who can no longer pause to wonder and stand rapt in awe, is as good as dead; his eyes are closed.",
        "You never fail until you stop trying.",
        "If you want to live a happy life, tie it to a goal, not to people or things.",
        "It is not that I'm so smart. But I stay with the questions much longer.",
        "Genius is 1% talent and 99% hard work.",
        "Weakness of attitude becomes weakness of character."
    )

    fun getFortune(): String {
        return fortunes[Random.nextInt(fortunes.size)]
    }
}
